"""AIsketcher: structured visual exploration and reproducible creative handoff."""

from __future__ import annotations

from .backends import (
    Backend,
    DiffusersBackend,
    DiffusersGenerationCancelled,
    FakeBackend,
)
from .config import (
    CONFIG_SCHEMA_VERSION,
    AIsketcherConfig,
    default_project_config_path,
    default_user_config_path,
    load_config,
    load_config_file,
    save_config,
)
from .controls import diagnose, make_canny, prepare
from .errors import (
    AIsketcherError,
    GenerationError,
    IntegrityError,
    ModelUnavailableError,
    OptionalDependencyError,
    RemovedFeatureError,
    ReplayError,
    UnsafeModelError,
    UnsupportedCapabilityError,
    ValidationError,
)
from .flux2_backend import (
    Flux2GenerationCancelled,
    Flux2KleinBackend,
    Flux2KleinModelConfig,
    Flux2KleinSettings,
    Flux2Progress,
)
from .model_registry import (
    CURATED_MODEL_PROFILES,
    MODEL_ARTIFACTS,
    AutoRoute,
    ControlType,
    CuratedModelProfile,
    HashPolicy,
    InputMode,
    ModelArtifact,
    ModelStatus,
    RuntimeFamily,
    VerifiedFile,
    get_model_profile,
    zero_click_profiles,
)
from .models import (
    BackendCapabilities,
    Candidate,
    CannyConfig,
    CapabilityIssue,
    CapabilityReport,
    CapabilitySeverity,
    GenerationRequest,
    GenerationResult,
    Intent,
    ModelReference,
    PreparationDiagnostics,
    PreparedSketch,
    Recipe,
    ReplayMode,
    ReplayReport,
    ResolvedRecipe,
    SeedMode,
    SeedPlan,
    StructureMode,
    TechnicalScores,
    VariationStrength,
)
from .presets import (
    PRESETS,
    InstallItem,
    InstallPlan,
    InstallResult,
    PresetDefinition,
    PresetManager,
    get_preset,
)
from .prompt_normalization import (
    DESIGN_EDIT_PROMPT_TEMPLATE,
    MARIAN_KO_EN_DOWNLOAD_BYTES,
    MARIAN_KO_EN_MODEL_ID,
    MARIAN_KO_EN_REVISION,
    MARIAN_KO_EN_WEIGHTS_SHA256,
    KoreanEnglishTranslator,
    MarianKoreanEnglishTranslator,
    NormalizedPrompt,
    PromptNormalizationStatus,
    TranslationSetupCancelled,
    TranslatorMetadata,
    contains_hangul,
    enhance_design_edit_prompt,
    normalize_prompt,
)
from .studio import Studio
from .study import Study

__version__ = "0.3.0"

__all__ = [
    "AIsketcherError",
    "AIsketcherConfig",
    "Backend",
    "BackendCapabilities",
    "Candidate",
    "CannyConfig",
    "CapabilityIssue",
    "CapabilityReport",
    "CapabilitySeverity",
    "CONFIG_SCHEMA_VERSION",
    "DESIGN_EDIT_PROMPT_TEMPLATE",
    "DiffusersBackend",
    "DiffusersGenerationCancelled",
    "FakeBackend",
    "Flux2GenerationCancelled",
    "Flux2KleinBackend",
    "Flux2KleinModelConfig",
    "Flux2KleinSettings",
    "Flux2Progress",
    "GenerationRequest",
    "GenerationResult",
    "GenerationError",
    "InstallItem",
    "InstallPlan",
    "InstallResult",
    "IntegrityError",
    "Intent",
    "InputMode",
    "KoreanEnglishTranslator",
    "MARIAN_KO_EN_MODEL_ID",
    "MARIAN_KO_EN_REVISION",
    "MARIAN_KO_EN_DOWNLOAD_BYTES",
    "MARIAN_KO_EN_WEIGHTS_SHA256",
    "MarianKoreanEnglishTranslator",
    "ModelReference",
    "ModelArtifact",
    "ModelStatus",
    "ModelUnavailableError",
    "OptionalDependencyError",
    "PRESETS",
    "CURATED_MODEL_PROFILES",
    "MODEL_ARTIFACTS",
    "NormalizedPrompt",
    "PreparationDiagnostics",
    "PreparedSketch",
    "PresetDefinition",
    "PresetManager",
    "PromptNormalizationStatus",
    "TranslationSetupCancelled",
    "Recipe",
    "RemovedFeatureError",
    "ReplayError",
    "ReplayMode",
    "ReplayReport",
    "ResolvedRecipe",
    "SeedMode",
    "SeedPlan",
    "StructureMode",
    "Studio",
    "Study",
    "TechnicalScores",
    "TranslatorMetadata",
    "AutoRoute",
    "ControlType",
    "CuratedModelProfile",
    "HashPolicy",
    "RuntimeFamily",
    "UnsafeModelError",
    "UnsupportedCapabilityError",
    "ValidationError",
    "VariationStrength",
    "VerifiedFile",
    "diagnose",
    "contains_hangul",
    "default_project_config_path",
    "default_user_config_path",
    "get_preset",
    "get_model_profile",
    "enhance_design_edit_prompt",
    "make_canny",
    "load_config",
    "load_config_file",
    "normalize_prompt",
    "prepare",
    "save_config",
    "zero_click_profiles",
]
