"""AIsketcher: structured visual exploration and reproducible creative handoff."""

from __future__ import annotations

from .backends import Backend, DiffusersBackend, FakeBackend
from .config import (
    CONFIG_SCHEMA_VERSION,
    AIsketcherConfig,
    default_project_config_path,
    default_user_config_path,
    load_config,
    load_config_file,
    save_config,
)
from .controls import diagnose, make_canny, prepare
from .errors import (
    AIsketcherError,
    GenerationError,
    IntegrityError,
    ModelUnavailableError,
    OptionalDependencyError,
    RemovedFeatureError,
    ReplayError,
    UnsafeModelError,
    UnsupportedCapabilityError,
    ValidationError,
)
from .models import (
    BackendCapabilities,
    Candidate,
    CannyConfig,
    CapabilityIssue,
    CapabilityReport,
    CapabilitySeverity,
    GenerationRequest,
    GenerationResult,
    Intent,
    ModelReference,
    PreparationDiagnostics,
    PreparedSketch,
    Recipe,
    ReplayMode,
    ReplayReport,
    ResolvedRecipe,
    SeedMode,
    SeedPlan,
    StructureMode,
    TechnicalScores,
    VariationStrength,
)
from .presets import (
    PRESETS,
    InstallItem,
    InstallPlan,
    InstallResult,
    PresetDefinition,
    PresetManager,
    get_preset,
)
from .studio import Studio
from .study import Study

__version__ = "0.2.1"

__all__ = [
    "AIsketcherError",
    "AIsketcherConfig",
    "Backend",
    "BackendCapabilities",
    "Candidate",
    "CannyConfig",
    "CapabilityIssue",
    "CapabilityReport",
    "CapabilitySeverity",
    "CONFIG_SCHEMA_VERSION",
    "DiffusersBackend",
    "FakeBackend",
    "GenerationRequest",
    "GenerationResult",
    "GenerationError",
    "InstallItem",
    "InstallPlan",
    "InstallResult",
    "IntegrityError",
    "Intent",
    "ModelReference",
    "ModelUnavailableError",
    "OptionalDependencyError",
    "PRESETS",
    "PreparationDiagnostics",
    "PreparedSketch",
    "PresetDefinition",
    "PresetManager",
    "Recipe",
    "RemovedFeatureError",
    "ReplayError",
    "ReplayMode",
    "ReplayReport",
    "ResolvedRecipe",
    "SeedMode",
    "SeedPlan",
    "StructureMode",
    "Studio",
    "Study",
    "TechnicalScores",
    "UnsafeModelError",
    "UnsupportedCapabilityError",
    "ValidationError",
    "VariationStrength",
    "diagnose",
    "default_project_config_path",
    "default_user_config_path",
    "get_preset",
    "make_canny",
    "load_config",
    "load_config_file",
    "prepare",
    "save_config",
]
